services:
  postgres:
    container_name: PostgreSQL
    image: postgres:17-alpine
    restart: always
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 1s
      timeout: 1s
      retries: 30 # 재시도 30s

  redis:
    container_name: Redis
    image: redis:7.4-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./db/redis/data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  liquibase:
    container_name: PostgreSQL-Liquibase
    image: liquibase/liquibase:4.29
    depends_on:
      postgres: # PostgreSQL이 모두 로드된 이후 Liquibase를 시작하도록 설정합니다.
        condition: service_healthy
    volumes:
      - ./liquibase/changelog:/liquibase/changelog
    command: >
      --changeLogFile=/changelog/changelog-config.yml
      --url=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      --username=${POSTGRES_USER}
      --password=${POSTGRES_PASSWORD}
      update